print("     *")
print("    * *")
print("   *   *")
print("  *     *")
print(" *       *")
print("****   ****")
print("   *   *")
print("   *   *")
print("   *   *")
print("   *****")

print("  ")
for i in range(10):
    print("Ewa")
    print("<<>>")